apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: query-twitter
spec:
  type: bindings.twitter
  metadata:
  - name: consumerKey
    secretKeyRef:
      name: twitter-secret
      key: consumerKey
  - name: consumerSecret
    secretKeyRef:
      name: twitter-secret
      key: consumerSecret
  - name: accessToken
    secretKeyRef:
      name: twitter-secret
      key: accessToken
  - name: accessSecret
    secretKeyRef:
      name: twitter-secret
      key: accessSecret
scopes:
- nginx-ingress