apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-queue
  namespace: order
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
scopes:
- order-auditor
- workflows
- order-viewer