apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-events
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: password
  - name: allowedTopics
    value: "messages"
scopes:
- nginx-ingress
- http-event-subscriber