apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-event-subscriber
  labels:
    app: http-event-subscriber
    demo: http-event
spec:
  selector:
    matchLabels:
      app: http-event-subscriber
  template:
    metadata:
      labels:
        app: http-event-subscriber
        demo: http-event
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "http-event-subscriber"
        dapr.io/app-port: "8080"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: service
        image: mchmarny/http-event-subscriber:v0.11.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: PUBSUB_NAME
          value: "http-events"
        - name: TOPIC_NAME
          value: "messages"