apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: email
spec:
  type: bindings.twilio.sendgrid
  metadata:
  - name: emailFrom
    value: "demo@thingz.io"
  - name: subject
    value: "Demo Email Subject"
  - name: apiKey
    value: <YOUR_SENDGRID_API_KEY>