---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: ingress-config
spec:
  tracing:
    samplingRate: "1"
  secrets:
    scopes:
      - storeName: kubernetes
        defaultAccess: deny
        allowedSecrets: ["dapr-api-token"]
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"