{
 "title": "Dapr Sidecar Dashboard",
 "tags": [ "autosetup" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "NAMESPACE",
    "query": "label_values(dapr_runtime_component_loaded,kubernetes_namespace)"
   },
   {
    "name": "dapr_app_id",
    "label": "APPID",
    "query": "label_values(dapr_runtime_component_loaded,app_id)"
   }
  ]
 },
 "panels": [
  { "title": "Health monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sidecar uptime",
   "type": "stat",
   "description": "This shows the uptime of dapr runtime sidecar. If the sidecar is running for less than 10 minutes, the color will turn into RED.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total CPU usage (Kernel and User)",
   "type": "graph",
   "description": "This shows total amount of Kernel and user CPU usage for Daprd.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"($dapr_app_id).*\", namespace=\"$namespace\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Number of GO routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{kubernetes_name=~\"($dapr_app_id)-dapr.*\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Memory usage in bytes",
   "type": "graph",
   "description": "The amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Managed virtual memory in bytes",
   "type": "graph",
   "description": "The amount of address space that a process is managing. This includes all types of memory, both in RAM and swapped out.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{kubernetes_name=~\"($dapr_app_id)-dapr\", kubernetes_namespace=\"$namespace\"}) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Throughput/Latency - HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound request latency (App->Dapr) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the turn-around latency when user app calls Dapr API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_server_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{method}} {{path}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_server_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{method}} {{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Outbound request rate (App -> Dapr) (RPS)",
     "type": "graph",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_server_response_count{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{method}} {{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request latency (Dapr -> App) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[95p] {{method}} /{{path}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_http_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, method, path))",
       "legendFormat": "[75p] {{method}} /{{path}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request rate (Dapr -> App) (RPS)",
     "type": "graph",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app HTTP endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, method, path) (rate(dapr_http_client_completed_count{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{method}} {{path}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput/Latency - gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outbound request latency (App->Dapr) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the turn-around latency when user app calls Dapr API. For example, you can understand each statestore and service invocation performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_grpc_io_server_server_latency_bucket{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_server_method))",
       "legendFormat": "[95p] - {{grpc_server_method}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_grpc_io_server_server_latency_bucket{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_server_method))",
       "legendFormat": "[75p] {{grpc_server_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Outbound request rate (App -> Dapr) (RPS)",
     "type": "graph",
     "description": "This charts shows completed request rate (rps) when User app calls Dapr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, grpc_server_method, grpc_server_status) (rate(dapr_grpc_io_server_completed_rpcs{app_id=~\"$dapr_app_id\", grpc_server_method=~\"dapr.Dapr/.*\"}[5m]))",
       "legendFormat": "{{grpc_server_status}} {{grpc_server_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request latency (Dapr -> App) (95p, 75p)",
     "type": "graph",
     "description": "This charts shows the inbound request latency from Dapr to App. You can analyze App's API endpoint performance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_client_method))",
       "legendFormat": "[95p] {{grpc_client_method}} ({{app_id}})"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m])) by (le, app_id, grpc_client_method))",
       "legendFormat": "[75p] {{grpc_client_method}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Inbound request rate (Dapr -> App) (RPS)",
     "type": "graph",
     "description": "This charts shows request rate (rps) when Dapr runtime calls User app gRPC endpoints.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (app_id, grpc_client_method, grpc_client_status) (rate(dapr_grpc_io_client_roundtrip_latency_bucket{app_id=~\"$dapr_app_id\", grpc_client_method=~\"daprclient.DaprClient/.*\", kubernetes_namespace=\"$namespace\"}[5m]))",
       "legendFormat": "{{grpc_client_status}} {{grpc_client_method}} ({{app_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loaded component configurations",
     "type": "stat",
     "description": "This shows the number of configured components. For example, it will shows \"2\" if you configure redis statestore and redis pubsub components. ",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_loaded{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id)",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Initialized components",
     "type": "stat",
     "description": "This shows the number of initialized components. This number must be the same as loaded components. Otherwise, Daprd fails to initialize some of components.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_init_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id)",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "Component failures",
     "type": "graph",
     "description": "This chart shows the number component initialization failures with the reasons.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dapr_runtime_component_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{app_id}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status report status",
     "type": "graph",
     "description": "This shows when Daprd reports host status to placement service. Non-Actor service reports host status in the beginning. Actor service reports host status to placement periodically. If there is a failure, virtual actors will not be distributed properly.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_actor_status_report_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK ({{app_id}})"
      },
      {
       "expr": "rate(dapr_runtime_actor_status_report_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error ({{app_id}})"
      }
     ]
    },
    {
     "title": "Report status error reasons",
     "type": "bargauge",
     "description": "This shows the failures when Daprd reports host status to placement.",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 18 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_actor_status_report_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, operation)",
       "legendFormat": "{{operation}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Placement table operation",
     "type": "graph",
     "description": "This shows the placement table update status based on the response from placement service. Daprd maintains the actor placement table in its memory. This table is periodically updated.",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(dapr_runtime_actor_table_operation_recv_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, operation)",
       "legendFormat": "{{operation}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Actor Deactivation",
     "type": "graph",
     "description": "This chart shows how many actors are deactivated.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dapr_runtime_actor_deactivated_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "OK {{actor_type}}"
      },
      {
       "expr": "dapr_runtime_actor_deactivated_failed_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "Error {{actor_type}}"
      }
     ]
    },
    {
     "title": "Actor table rebalancing",
     "type": "graph",
     "description": "This shows when actor is rebalanced. This operation can make the activated actors deactivated and move actor to the other hosts.",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dapr_runtime_actor_rebalanced_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}",
       "legendFormat": "{{app_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "mTLS initialization status",
     "type": "graph",
     "description": "This chart  shows when mTLS is initialized, which means root cert is loaded and workload cert is issued from sentry, when runtime starts.",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_mtls_init_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK {{app_id}}"
      },
      {
       "expr": "rate(dapr_runtime_mtls_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error {{app_id}}"
      }
     ]
    },
    {
     "title": "mTLS Initialization Errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 11 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_mtls_init_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{reason}} ({{app_id}})"
      }
     ]
    },
    {
     "title": "Workload certificate rotation status",
     "type": "graph",
     "description": "This chart shows when workload certificate is rotated.",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(dapr_runtime_mtls_workload_cert_rotated_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "OK {{app_id}}"
      },
      {
       "expr": "rate(dapr_runtime_mtls_workload_cert_rotated_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}[5m])",
       "legendFormat": "Error {{app_id}}"
      }
     ]
    },
    {
     "title": "Cert rotation error reasons",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
     "targets": [
      {
       "expr": "sum(dapr_runtime_mtls_workload_cert_rotated_fail_total{app_id=~\"$dapr_app_id\", kubernetes_namespace=\"$namespace\"}) by (app_id, reason)",
       "legendFormat": "{{reason}} ({{app_id}})"
      }
     ]
    }
   ]
  }
 ]
}